# Generated by Django 2.1.7 on 2019-06-24 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RulesForMono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.IntegerField(default=0, max_length=3)),
                ('rules_for_computation', models.TextField(max_length=100, null=True)),
                ('fields_for_observation', models.TextField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'rules_for_mono',
            },
        ),
        migrations.CreateModel(
            name='TableSets',
            fields=[
                ('Tid', models.AutoField(primary_key=True, serialize=False)),
                ('instance_name', models.CharField(max_length=15)),
                ('database_name', models.CharField(max_length=15)),
                ('table_name', models.CharField(max_length=15)),
                ('user_name', models.CharField(max_length=15)),
                ('divided', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'table_sets',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tablesets',
            unique_together={('database_name', 'table_name')},
        ),
        migrations.AddField(
            model_name='rulesformono',
            name='related_tables',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='check.TableSets'),
        ),
    ]
