# Generated by Django 2.1.7 on 2019-06-27 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesformono',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rulesformono',
            name='last_modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tablesets',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablesets',
            name='host',
            field=models.CharField(default='0.0.0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='tablesets',
            name='last_modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tablesets',
            name='port',
            field=models.IntegerField(default=20025),
        ),
        migrations.AlterField(
            model_name='rulesformono',
            name='fields_for_observation',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rulesformono',
            name='rule_type',
            field=models.CharField(choices=[('computation', '单库表数据校对'), ('observation', '单表状态维度校验')], default='computation', max_length=15),
        ),
        migrations.AlterField(
            model_name='rulesformono',
            name='rules_for_computation',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tablesets',
            name='database_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tablesets',
            name='table_name',
            field=models.CharField(max_length=45),
        ),
    ]
